LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := su
LOCAL_MODULE := phh-su
LOCAL_MODULE_CLASS := EXECUTABLES

LOCAL_INIT_RC := su.rc

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SuperSu
LOCAL_MODULE_OWNER := zuk
LOCAL_SRC_FILES := prebuilt/superuser_phh.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
include $(BUILD_PREBUILT)
